global:
  label:
    priorities:
      custom-labels: 1
      custom-labels-no-self-overlap: 2
      continent-labels: 3
      country-labels: 4
      country-small-labels: 5
      city-center-country-capital-category1: 6
      city-center-country-capital-category2: 7
      city-center-country-capital-category3: 8
      city-center-country-capital-category4: 9
      city-center-country-capital-category5: 10
      city-center-country-capital-category6: 11
      city-center-country-capital-category7: 12
      city-center-country-capital-category8: 13
      city-center-country-capital-category9: 14
      city-center-country-capital-category10: 15
      city-center-country-capital-category11: 16
      city-center-country-capital-category12: 17
      city-center-country-capital-category13: 18
      city-center-country-capital-category14: 19
      city-center-country-capital-category15: 20
      state-labels: 21
      city-center-state-capital-category1: 22
      city-center-state-capital-category2: 23
      city-center-state-capital-category3: 24
      city-center-state-capital-category4: 25
      city-center-state-capital-category5: 26
      city-center-state-capital-category6: 27
      city-center-state-capital-category7: 28
      city-center-state-capital-category8: 29
      city-center-state-capital-category9: 30
      city-center-state-capital-category10: 31
      city-center-state-capital-category11: 32
      city-center-state-capital-category12: 33
      city-center-state-capital-category13: 34
      city-center-state-capital-category14: 35
      city-center-state-capital-category15: 36
      city-center-county-capital-category1: 37
      city-center-county-capital-category2: 38
      city-center-county-capital-category3: 39
      city-center-county-capital-category4: 40
      city-center-county-capital-category5: 41
      city-center-county-capital-category6: 42
      city-center-county-capital-category7: 43
      city-center-county-capital-category8: 44
      city-center-county-capital-category9: 45
      city-center-county-capital-category10: 46
      city-center-county-capital-category11: 47
      city-center-county-capital-category12: 48
      city-center-county-capital-category13: 49
      city-center-county-capital-category14: 50
      city-center-county-capital-category15: 51
      city-center-category1: 52
      city-center-category2: 53
      city-center-category3: 54
      city-center-category4: 55
      city-center-category5: 56
      city-center-category6: 57
      city-center-category7: 58
      city-center-category8: 59
      city-center-category9: 60
      city-center-category10: 61
      city-center-category11: 62
      city-center-category12: 63
      city-center-category13: 64
      city-center-category14: 65
      city-center-category15: 66
      truck-icon-general_truck_restriction: 67
      truck-icon-height_restriction: 68
      truck-icon-weight_restriction: 69
      truck-icon-weight_per_axle_restriction: 70
      truck-icon-width_restriction: 71
      truck-icon-length_restriction: 72
      truck-icon-axle_number_restriction: 73
      truck-icon-length_restriction_kpra: 74
      truck-icon-hazmat_any: 75
      truck-icon-hazmat_goods_harmful_for_water: 76
      truck-icon-hazmat_explosive_flammable: 77
      truck-icon-hazmat_explosives: 78
      truck-icon-hazmat_gas: 79
      truck-icon-hazmat_flammable: 80
      truck-icon-hazmat_flammable_solid_combustible: 81
      truck-icon-hazmat_organic: 82
      truck-icon-hazmat_poison: 83
      truck-icon-hazmat_poisonous_inhalation_hazard: 84
      truck-icon-hazmat_radioactive: 85
      truck-icon-hazmat_corrosive: 86
      truck-icon-hazmat_tunnel_category: 87
      truck-icon-hazmat_other: 88
      truck-icon-hazmat_unspecified: 89
      truck-icon-hazmat_permit_required: 90
      truck-icon-trailer_type: 91
      truck-icon-speed_limit: 92
      city-center-neighbourhood: 93
      mountain-range-labels: 94
      japan-annotation-geo-labels: 95
      japan-annotation-mountain-peak-labels: 96
      japan-mountain-peak-labels: 97
      japan-annotation-governmental-office-labels: 98
      japan-governmental-office-labels: 99
      japan-annotation-public-transport-labels: 103
      japan-public-transport-labels: 104
      japan-annotation-road-facility-labels: 125
      japan-road-facility-labels: 126
      japan-city-center-oaza: 133
      japan-city-center-aza: 134
      japan-annotation-traffic-light-labels: 135
      japan-traffic-light-labels: 136
      city-center-microhood: 138
      city-center-hamlet: 139
      ocean-labels: 140
      sea-labels: 141
      truck-labels: 142
      traffic-icon-road_closure: 144
      traffic-icon-accident: 145
      traffic-icon-disabled_vehicle: 146
      traffic-icon-road_hazard: 147
      traffic-icon-construction: 148
      traffic-icon-congestion: 149
      traffic-icon-planned_event: 150
      traffic-icon-mass_transit: 151
      traffic-icon-weather: 152
      traffic-icon-other: 153
      safetycamera: 154
      low-emission-zone-labels: 155
      japan-annotation-poi-labels: 156
      poi-labels: 157
      japan-city-center-microhood-block: 392
      japan-speed-rail-labels: 393
      japan-state-rail-labels: 394
      japan-private-rail-labels: 395
      japan-subway-rail-labels: 396
      japan-tram-rail-labels: 397
      japan-gondola-labels: 398
      japan-cable-car-labels: 399
      road0-labels: 400
      road1-labels: 401
      road2-labels: 402
      road3-labels: 403
      road4-labels: 404
      walkway-labels: 405
      pedestrian-labels: 406
      island-labels: 407
      rail-labels: 408
      chairlift-labels: 409
      skirundownhill-labels: 410
      japan-annotation-ferry-labels: 411
      ferry-labels: 412
      japan-annotation-buildings-info-labels: 413
      buildings-info-labels: 414
      japan-city-center-microhood-parcel: 415
      buildings-address-labels: 416
      large-land-use-labels: 417
      mountain-peak-labels: 418
      land-cover-labels: 419
      japan-annotation-small-land-use-labels: 420
      small-land-use-labels: 421
      water-labels: 422
      road-shield-labels: 423
      road-shield0-labels: 424
      road-shield1-labels: 425
      road-shield2-labels: 426
      road-shield3-labels: 427
      road-shield4-labels: 428
      custom-labels-overlap-all: 429
      border-line-labels: 430
      one-way-arrow-labels: 431
